### ISSUE TITLE
Google 表單失效 | 關於「行動電源」的釋義有誤

### ISSUE THREAD

**Issue by BreadKi11er** [caris-events/invade#2]
該表單失效：https://forms.gle/YoymRXnZYk4VVWrn9

另，對於 [Power bank](https://baka-invade.org/dict/%E5%B0%BF%E8%A2%8B/) 一物，「尿袋」一般爲香港（粵語）的用詞，在中國大陸很少使用（即使在粵語地區）該詞，淘寶等電商絕大多數都稱爲「移动电源、充电宝」，可見 [wikipedia](https://zh.wikipedia.org/zh-cn/%E8%A1%8C%E5%8B%95%E9%9B%BB%E6%BA%90)。

**Comment by YamiOdymel** [comment]
感謝分享，網站正在重新設計、加強，預計年底更新之後
會再將這個異動更新回去

**Comment by YamiOdymel** [comment]
網站已更新，謝謝。
